### ISSUE TITLE
Help for decrypting

### ISSUE THREAD

**Issue by RealDarkCraft** [Elysia-simp/AC-ZDAT#1]
Hey i'm wandering if you know what type of encryption the game use (like for save)

**Comment by Elysia-simp** [comment]
Hello, I really don't know what kind of encryption the save data would use. I only know decryption with Asset bundles is XOR.

**Comment by RealDarkCraft** [comment]
thanks, also do you have an idea where could be the XOR key (or even just his size) ?

**Comment by Elysia-simp** [comment]
Manifest contains XOR keys for bundles, but I never figured out how to use them. The key was 1 byte so I always just bruteforced it.

**Comment by RealDarkCraft** [comment]
> Manifest contains XOR keys for bundles, but I never figured out how to use them. The key was 1 byte so I always just bruteforced it.

I found the key in a wip save editor for the game, also the xor key is 1000 byte length
