### ISSUE TITLE
Idea to decrypt file without manifest

### ISSUE THREAD

**Issue by RealDarkCraft** [Elysia-simp/AC-ZDAT#2]
since ZDAT always start with "ZDAT" magic and that the key is only 1 byte, i think we can do :
(input file first byte) ^ ord("Z")
and this should give the xor key

**Comment by Elysia-simp** [comment]
Wrong idea, right track. It's just asset bundles, they always have a header of UnityFS so the code  would be more like 

            byte[] decryptedKey = new byte[key_len];
            for (int i = 0; i < key_len; i++)
            {
                decryptedKey[i] = (byte)(bruteKey[i] ^ masterKey[i % masterKey.Length]); // i only need the one
            }

            byte[] decryptedData = new byte[encryptedData.Length];
            for (int i = 0; i < encryptedData.Length; i++)
            {
                decryptedData[i] = (byte)(encryptedData[i] ^ decryptedKey[i % decryptedKey.Length]);
            }

But I see your point, I will implement it in a little bit. I didn't out of pure laziness.

**Comment by Elysia-simp** [comment]
Has been implemented, thank you for your patience.
